-- Demo schema: orders, order_items, products, customers
CREATE TABLE products (
  product_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(100), price NUMBER(10,2), category VARCHAR2(50)
);
CREATE TABLE customers (
  customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(100), email VARCHAR2(200), city VARCHAR2(100)
);
CREATE TABLE orders (order_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,customer_id NUMBER NOT NULL, order_ts TIMESTAMP DEFAULT SYSTIMESTAMP, status VARCHAR2(20),
  CONSTRAINT fk_orders_cust FOREIGN KEY (customer_id) REFERENCES customers(customer_id)
);
CREATE TABLE order_items (
  order_id NUMBER NOT NULL,
  product_id NUMBER NOT NULL,
  qty NUMBER(10),
  price NUMBER(10,2),
  CONSTRAINT pk_order_items PRIMARY KEY (order_id, product_id),
  CONSTRAINT fk_items_order FOREIGN KEY (order_id) REFERENCES orders(order_id),
  CONSTRAINT fk_items_prod FOREIGN KEY (product_id) REFERENCES products(product_id)
);
CREATE INDEX idx_orders_ts ON orders(order_ts);
